# Generated by Django 4.2 on 2026-09-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_active'], name='product_catalog_idx'),
        ),
    ]
